### ISSUE TITLE
win7下面加载字库失败

### ISSUE THREAD

**Issue by toby20130333** [penk/qml-handwriting#1]
if (!data.recognizer->open("handwriting-zh_CN.model")){
        qDebug("can't load model file");
    }else {
        qDebug("model \"handwriting-zh_CN.model\" loaded");
    }
无法正确加载字库，想问下@penk 如何处理，是否目前只针对unix系统处理呢？

**Comment by toby20130333** [comment]
找到解决办法就是修改源码，针对windows平台模块加载文件的修复

**Comment by penk** [comment]
對, 請指定 Windows 平台上 "handwriting-zh_CN.model" 檔案的路徑.
